#! /bin/sh
#
# init.d script to configure device as a access point (AP) 
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="set-up and start as access point"
MODE_FILE=/etc/default/wifi-mode


# Gracefully exit if the package has been removed.
# If the file /etc/default/wifi-mode is not present then exit gracefully.
#
test -e $MODE_FILE || exit 0


start() 
{
  # We have to handle the option of two possible WNIC chipsets. Broadcom and Reaaltek
	# This is strange. I've seen in tests two different product ids for the Broadcom chipset
	# as bd17 and 0bdc. 
  WNIC=`lsusb | awk ' $6 == "0a5c:bd17" { print "broadcom";next } $6 == "0a5c:0bdc" {print "broadcom";next} $6 == "0bda:018a" { print "realtek";next } ' `

# echo $WNIC

  if [ "$WNIC" = "broadcom" ]; then

  	if [ ! -z $( pidof hostapd) ]; then $0 stop; fi

    # Modify the /etc/hostapd/hostapd.conf file appropriately
    sed -i 's/driver=.*/driver=nl80211/;s/manufacturer=.*/manufacturer=Broadcom/;s/device_name=.*/device_name=BRCM43236/' /etc/hostapd/hostapd.conf
  	hostapd -e /dev/random -B /etc/hostapd/hostapd.conf
		usleep 10000
  elif [ "$WNIC" = "realtek" ]; then

  	if [ ! -z $( pidof hostapd-rtl871xdrv ) ]; then $0 stop; fi

    sed -i 's/driver=.*/driver=rtl871xdrv/;s/manufacturer=.*/manufacturer=Realtek/;s/device_name=.*/device_name="Wireless AP"/' /etc/hostapd/hostapd.conf
  	hostapd-rtl871xdrv -P /var/run/hostapd-rtl871xdrv.pid -B /etc/hostapd/hostapd.conf
		usleep 10000
  fi 

	ip addr add $AP_IPADDR dev wlan0
	dnsmasq -C /etc/dnsmasq/dnsmasq.conf
}

stop()
{
	# Stop any running hostapd and dnsmasq processes
	if [ ! -z $(pidof hostapd) ]; then 
		echo "hosapd stopping ..."
		kill `pidof hostapd` 
	fi

	# Stop any running hostapd-rtl871xdrv and dnsmasq processes
	if [ ! -z $(cat /var/run/hostapd-rtl871xdrv.pid) ]; then 
		echo "hosapd-rtl871xdrv stopping ..."
		kill `cat /var/run/hostapd-rtl871xdrv.pid` 
	fi


	if [ ! -z "$(pidof dnsmasq)" ]; then 
		echo "dnsmasq stopping ..."
		killall dnsmasq 
	fi
}


# Read config file
if [ -r $MODE_FILE ]; then
	. $MODE_FILE

	if [ $WIFI_MODE != "AP" ]; then exit 0; fi

else
	exit 0
fi



case "$1" in
  start)
		start
	;;
  stop) 
		stop
	;;
  restart) echo "Restarting"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
