#!/bin/bash

# This script is run early on in the /etc/init.d sequence before there are any process started.
# A check is made for any file packages (with extension zip) in the directory /mnt/part7. 
# If found then the package is unzip and its assocaited 'install' script is envoked. The 
# contained 'install' script is responsible for installing its associated package.

# The install script writes its messages to the /mnt/part7/Install.log file.

# The install script exits with code 0 or 1 to indicate correct installation or error respectively.

# Partition layout on the SD card (nomial 8GB)

## Device                  start       end        Blocks    Id System
## /dev/mmcblk0p1            1281        3200       61440   c Win95 FAT32 (LBA) <--------------------- boot partition
## /dev/mmcblk0p2            3201       67200     2048000  83 Linux <--------------------------------- default root file system partition
## /dev/mmcblk0p3           67201      131200     2048000  83 Linux <--------------------------------- shadow root file system (if requried)
## /dev/mmcblk0p4          131201      236800     3379200   f Win95 Ext'd (LBA)
## /dev/mmcblk0p5          131265      176064     1433600  83 Linux <----------- Could be for customer data or perhaps a second shadow root partition
## /dev/mmcblk0p6          176065      220865     1433600  83 Linux <----------- Ditto as for partition 5
## /dev/mmcblk0p7          220865      236800      509951  83 Linux <----------- Used for upgrade/installation of existing / new software.


# This early on in the /etc/init.d sequence we may not have mounted the /mnt/part3 partition so we 
# check if it is present.

cat /etc/mtab | grep upgrade > /dev/null

if [ $? -eq 1 ]; then
  if [ -b /dev/mmcblk0p7 ]; then
    mkdir -p /mnt/upgrade
    echo "Mounting device /dev/mmcblk0p7"
    mount -t ext4 /mnt/mmcblk0p7 /mnt/upgrade
  fi
fi

# Potentially there may be more than one package to install. I've not tried this!
# In the case of multiple packages then name then say 01package.zip, 02package.zip etc to keep the installation order correct.
# For now, as of the 10/10/2016, there is only one package installed for each reboot.
for p in $( ls -1 /mnt/upgrade/*.zip); do

  echo "Package " $p

	# unzip the packge to directory Install
	cd /mnt/upgrade
  mkdir -p ./Install
  unzip -d ./Install $p

	# Run installation script
	cd ./Install
	./install

	# Tidy up
	cd ..
	rm -rf ./Install

	# Will delete the package, but for testing I'll kept it
	rm $p



done






