#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

	# Ignore dangling symlinks (if any).
  [ ! -f "$i" ] && continue

  case "$i" in
		*.sh)
	    # Source shell script for speed.
	    (
				trap - INT QUIT TSTP
				set start
				. $i
	    )
		;;
		*S01dofirst*)
			$i start
		;;

		*)
			# No sh extension, so fork subprocess.
	    $i start > /dev/null 2>&1
	  ;;
	esac
done

